### ISSUE TITLE
Popular tags in sidebar: missing blog route in buttons link when outside the blog

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-editorial#37] opened 2023-11-23 10:04 UTC
The button link doesn't work: it takes you back to the home page.
The links work when consulting the blog or an article, but not on other pages: the blog route should be added to the link for all pages other than the blog or articles.

Confirmed in demo site.

Maybe something to modify in partials/sidebar.html.twig `{% set new_base_url = blog.url == '/' ? '' : blog.url %}`
or in partials/taxonomylist.html.twig ?

**Comment by pmoreno-rodriguez** [comment] 2023-11-23 20:02
You are right. I will fix it as soon as possible. 
Thanks so much.

**Comment by Fazarel** [comment] 2023-11-24 14:58
If I may make a suggestion in passing: I'm not sure it's relevant to list the "featured" tag, since the publications are already displayed above with a "more featured posts" button.
Unfortunately I don't see an option in the Taxonomy List plugin to easily exclude tags from the list...

**Comment by pmoreno-rodriguez** [comment] 2023-11-24 21:25
> The button link doesn't work: it takes you back to the home page. The links work when consulting the blog or an article, but not on other pages: the blog route should be added to the link for all pages other than the blog or articles.
> 
> Confirmed in demo site.
> 
> Maybe something to modify in partials/sidebar.html.twig `{% set new_base_url = blog.url == '/' ? '' : blog.url %}` or in partials/taxonomylist.html.twig ?

Finally, after some testing, the problem was caused by inheritance between Twig templates. The sidebar template is inserted from base.html.twig, so I have inserted the line corresponding to the blog path in that file.

The origin of the problem was that within the sidebar, a reference was made to blog.url, which was not defined, outside the scope of the blog page.

Can you confirm that it works on the demo page?

**Comment by Fazarel** [comment] 2023-11-25 17:09
It seems to work fine now!

**Comment by pmoreno-rodriguez** [comment] 2023-11-25 20:12
Fixed in 2.0.5 release

**Closed by pmoreno-rodriguez** 2023-11-25 20:12 UTC
Labels: bug
